// Generated by npm run build. Do not edit by hand.


// update/updater-worker.ts
import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { chmod, readFile, rename, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import { setTimeout as delay } from "node:timers/promises";

// update/updater-policy.ts
var UPDATE_START_DELAY_MS = 5e3;
function updateStartDelay(environment = process.env) {
  return environment.IVA_FILE_DELIVERY_WORKER_DELAY_MS === "0" ? 0 : UPDATE_START_DELAY_MS;
}

// update/updater-worker.ts
var IVA_CLI = join(homedir(), ".local", "bin", "iva");
function run(args) {
  try {
    execFileSync(IVA_CLI, args, {
      stdio: "pipe",
      timeout: 20 * 60 * 1e3,
      maxBuffer: 2e6,
      env: process.env
    });
  } catch (error) {
    const failure = error;
    if (failure.code === "ENOENT") throw new Error("IVA_CLI_NOT_FOUND");
    if (failure.code === "ETIMEDOUT" || failure.signal === "SIGTERM")
      throw new Error("IVA_CLI_TIMEOUT");
    throw new Error("IVA_CLI_FAILED");
  }
}
async function save(path, job2) {
  const temporary = `${path}.${randomBytes(5).toString("hex")}.tmp`;
  await writeFile(temporary, `${JSON.stringify(job2, null, 2)}
`, {
    mode: 384
  });
  await chmod(temporary, 384);
  await rename(temporary, path);
}
async function installedSha(job2) {
  const parsed = JSON.parse(await readFile(job2.statePath, "utf8"));
  if (!parsed || typeof parsed !== "object" || !Array.isArray(parsed.plugins))
    return "";
  const entry = parsed.plugins.find(
    (item) => item?.name === job2.pluginName
  );
  return typeof entry?.sha === "string" ? entry.sha : "";
}
async function rollback(job2) {
  if (!/^[a-f0-9]{40}$/u.test(job2.previousSha)) return "failed";
  try {
    run(["plugin", "remove", job2.pluginName]);
    run(["plugin", "add", `${job2.sourceBase}@${job2.previousSha}`, "--trust"]);
    run(["doctor"]);
    return await installedSha(job2) === job2.previousSha ? "succeeded" : "failed";
  } catch {
    return "failed";
  }
}
var jobPath = process.argv[2];
if (!jobPath) process.exit(2);
var job = JSON.parse(await readFile(jobPath, "utf8"));
try {
  await delay(updateStartDelay());
  job.status = "running";
  job.startedAt = (/* @__PURE__ */ new Date()).toISOString();
  await save(jobPath, job);
  let stage = "plugin_update";
  try {
    run(["plugin", "update", job.pluginName]);
    stage = "sha_verification";
    const sha = await installedSha(job);
    if (sha !== job.expectedSha) throw new Error("SHA_MISMATCH");
    stage = "iva_doctor";
    run(["doctor"]);
    job.status = "succeeded";
    job.installedSha = sha;
    job.installedVersion = job.expectedVersion;
    job.message = "\u041F\u043B\u0430\u0433\u0438\u043D \u043E\u0431\u043D\u043E\u0432\u043B\u0451\u043D, \u0448\u0442\u0430\u0442\u043D\u0430\u044F \u0434\u0438\u0430\u0433\u043D\u043E\u0441\u0442\u0438\u043A\u0430 Iva \u043F\u0440\u043E\u0448\u043B\u0430.";
  } catch (error) {
    job.status = "failed";
    job.failureStage = stage;
    job.failureCode = error instanceof Error && /^[A-Z][A-Z0-9_]{2,80}$/u.test(error.message) ? error.message : "UPDATE_STEP_FAILED";
    const current = await installedSha(job);
    job.installedSha = current;
    if (current === job.expectedSha) job.installedVersion = job.expectedVersion;
    if (current === job.previousSha) job.installedVersion = job.previousVersion;
    if (current === job.expectedSha) {
      job.message = "\u041D\u043E\u0432\u0430\u044F \u0432\u0435\u0440\u0441\u0438\u044F \u0443\u0441\u0442\u0430\u043D\u043E\u0432\u0438\u043B\u0430\u0441\u044C, \u043D\u043E \u043D\u0435 \u043F\u0440\u043E\u0448\u043B\u0430 \u0434\u0438\u0430\u0433\u043D\u043E\u0441\u0442\u0438\u043A\u0443; \u0432\u044B\u043F\u043E\u043B\u043D\u044F\u0435\u0442\u0441\u044F \u0432\u043E\u0437\u0432\u0440\u0430\u0442 \u043F\u0440\u0435\u0434\u044B\u0434\u0443\u0449\u0435\u0439 \u0432\u0435\u0440\u0441\u0438\u0438.";
      job.rollbackStatus = await rollback(job);
      if (job.rollbackStatus === "succeeded") {
        job.status = "rolled_back";
        job.installedSha = job.previousSha;
        job.installedVersion = job.previousVersion;
        job.message = "\u041D\u043E\u0432\u0430\u044F \u0432\u0435\u0440\u0441\u0438\u044F \u043D\u0435 \u043F\u0440\u043E\u0448\u043B\u0430 \u043F\u0440\u043E\u0432\u0435\u0440\u043A\u0443; \u043F\u0440\u0435\u0434\u044B\u0434\u0443\u0449\u0430\u044F \u0432\u0435\u0440\u0441\u0438\u044F \u0432\u043E\u0441\u0441\u0442\u0430\u043D\u043E\u0432\u043B\u0435\u043D\u0430 \u0438 \u043F\u0440\u043E\u0432\u0435\u0440\u0435\u043D\u0430.";
      }
    } else if (current === job.previousSha) {
      job.rollbackStatus = "not_needed";
      job.message = "\u041E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0435 \u043D\u0435 \u043F\u0440\u0438\u043C\u0435\u043D\u0438\u043B\u043E\u0441\u044C; \u043F\u0440\u0435\u0434\u044B\u0434\u0443\u0449\u0430\u044F \u0440\u0430\u0431\u043E\u0447\u0430\u044F \u0432\u0435\u0440\u0441\u0438\u044F \u043E\u0441\u0442\u0430\u043B\u0430\u0441\u044C \u043D\u0430 \u043C\u0435\u0441\u0442\u0435.";
    } else {
      job.rollbackStatus = "unsafe_state";
      job.message = "\u041E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0438\u0435 \u0437\u0430\u0432\u0435\u0440\u0448\u0438\u043B\u043E\u0441\u044C \u0432 \u043D\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043D\u043E\u043C \u0441\u043E\u0441\u0442\u043E\u044F\u043D\u0438\u0438; \u0430\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438\u0439 remove/add \u043D\u0435 \u0432\u044B\u043F\u043E\u043B\u043D\u044F\u043B\u0441\u044F.";
    }
  }
  job.finishedAt = (/* @__PURE__ */ new Date()).toISOString();
  await save(jobPath, job);
} finally {
  if (typeof job.lockPath === "string") await rm(job.lockPath, { force: true });
}
