import { mkdir, readFile, writeFile } from "node:fs/promises";
import { build } from "esbuild";

const entries = [
  { input: "update/main.ts", output: "plugin/update-server.mjs" },
  { input: "update/updater-worker.ts", output: "plugin/update-worker.mjs" },
];

await mkdir("plugin", { recursive: true });
for (const entry of entries) {
  await build({
    entryPoints: [entry.input],
    outfile: entry.output,
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node24",
    sourcemap: false,
    legalComments: "eof",
    banner: {
      js: "// Generated by npm run build. Do not edit by hand.\n",
    },
  });
  const bundled = await readFile(entry.output, "utf8");
  await writeFile(entry.output, bundled.replace(/[ \t]+$/gmu, ""));
}
